### ISSUE TITLE
Remove the math namespace

### ISSUE THREAD

**Issue by stasm** [michalbe/cervus#34]
`core/math` could simply `export const vec3 = ...;` and `export const mat4 = ...'`. This will allow the following usage in other files: `import { vec3 } from './core/math'; vec3.method_name();`.

**Comment by michalbe** [comment]
Sure. This won't be a huge boost for us since we already use almost everything from `math` in the `Entity`, but it sounds like a reasonable thing to do.
I think that we can merge `math` with `misc`, default vectors can be used in place of `vec3.create` (are we still using this anywhere?) and `utils/hex_to_vec` is exported in `math` anyways.

**Comment by stasm** [comment]
We're using `vec3.from_values()` in a few places, which I'd like to rename to `vec3.of`. It's shorter and more in line with ECMA's Array methods.

I like the idea of merging `math` and `misc`! We could perhaps fix #24 along the way, too, by adding: `vec3.zero`, `vec3.unit`, `vec3.left`, `vec3.up`, `vec3.forward`.
